# Site settings
title: 姗姗来迟
email: 33@33coming.com
description: > # this means to ignore newlines until "baseurl:"
  姗姗来迟是 珊珊来了科技公司的旗下.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.33coming.com" # the base hostname & protocol for your site
twitter_username: 33coming
github_username:  33coming

# Build settings
markdown: kramdown

# my-value
my-statement_2: hahahah...